# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: myapp
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - go-service-with-metrics:8080